---

# - become: yes
#   debug:
#     var: ansible_user_dir

- name: Setup mysql
  include: mysql.yml

- name: Setup mattermost
  include: mattermost.yml

- name: Setup nginx
  include: nginx.yml

- name: Ensure mysql running
  become: yes
  systemd: name=mysql state=started

- name: Ensure mattermost running
  become: yes
  systemd: name=mattermost state=started
