---

- include_vars: file=vars/vars.yml

# - debug: "msg={{ smtp_password }}"

- import_tasks: mysql.yml
- import_tasks: mattermost.yml
- import_tasks: nginx.yml

- name: Ensure mysql running
  become: yes
  systemd: name=mysql state=started

- name: Ensure mattermost running
  become: yes
  systemd: name=mattermost state=started daemon_reload=yes

- import_tasks: extra.yml
