---

- name: Install mysql 5.7
  become: yes
  apt:
    name: [mysql-server, python3-pymysql]
    state: present
    update_cache: yes

- name: Create database
  become: yes
  mysql_db:
    name: mattermost
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add db user
  become: yes
  mysql_user:
    name: mmuser
    password: "{{ mattermost_mysql_user_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
    priv: mattermost.*:ALTER,CREATE,DELETE,DROP,INDEX,INSERT,SELECT,UPDATE